language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

env:
  global:
    - CORE_BRANCH=stable10
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

sudo: true
before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh serverinfo $CORE_BRANCH $DB

script:
  # Test lint
  - cd ../server
  - cd apps/serverinfo
  - find . -name \*.php -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
  fast_finish: true
